#! /bin/sh

sxhkd &
xcompmgr &

sh "/home/unix/.fehbg" &
sh -c '/home/unix/Projects/dotfiles/lemonbar.sh | lemonbar -g "1920x30+0+0" -u 3 -U "#ff2bd5"' &

xsetroot -cursor_name left_ptr &
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          12

bspc config normal_border_color "#800085"
bspc config focused_border_color "#ad00b3"

# bspc config split_ratio          0.52
# bspc config borderless_monocle   true
# bspc config gapless_monocle      true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

xset b off &
xset s off
xset -dpms
xset s noblank
setxkbmap "us,ru" ",winkeys" "grp:alt_shift_toggle"
